baseurl = "http://example.org"
title = "MBC Électrique"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "fr"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = 'MBC Électrique inc.'
  logoimage = "/images/logo.png"
  copyright = "mbcelectrique"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/mbcelectrique/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[languages]
[languages.fr]
languageName = "Français"
weight = 1

[languages.en]
languageName = "English"
weight = 2
description = 'MBC Électrique inc.'
